# -*- coding: utf-8 -*-
"""
Created on Fri Dec 11 13:31:47 2020

Mode generation class

@author: Marcos

"""
from . import toolbox as mgcl
from numpy import *
import numpy as np
from typing import cast
try:
    import cupy as cp
except ModuleNotFoundError:
   print("Cupy module couldn't be imported")

class LGmodes():
    """
    Creates an object that can contain and create LGmodes:
        Input parameters:
            - mfd = mode field diameter of the funtamental mode
            - group = number of groups
            - N = number of samples in of the axis Ex: 1080 --> 1080x1080 modes
            - px_size = step size 
            - generateModes:{True or False} -- if you want to generate the modes when the object is created
            - wholeSet = {True or False} -- if you want to generate all mode pyramid or half (no complex conj)
            - targetCore = {'GPU' or 'CPU'} 
            - multicore = {true or false} -- CPU computations done in parallel by numba and Ipyrallel if coreTarget is CPU
                    GPU:True uses cupy and numba
                    CPU:True uses Ipyparallel and numba
        Output parameters:
            - index = modes coefs
            - farfieldGouyPhase = Gouy phase at the farfield
            - LGmodesArray = Array with the modes
            - LGmodesArray__ = Array with the whole set of modes
            - LGmodesArrayFarField = Array with the modes at the farfield ( Including Gouy phase )
            - LGmodesArrayFarField__ = Array with the whole set of modes at the farfield ( Including Gouy phase )
            
    """
    
    def __init__(self,mfd,group,N,px_size, generateModes = True, wholeSet = False, farfield= False , engine = 'GPU', multicore = True):
        #Input atributes
        self.w0 = mfd/2
        self.group = group
        self.N = N 
        self.px_size = px_size
        
        #AutoGenerated atributes and constructor
        xx = mgcl.np.arange(-N//2,N//2,1) * px_size
        self.X,self.Y = mgcl.np.meshgrid(xx,xx)     
        self.index = mgcl.np.array([0])
        # GPU engine computes on device but LGmodes_GPU returns host numpy arrays by default.
        self.LGmodesArray: np.ndarray | None = None
        self.LGmodesArrayFarField: np.ndarray | None = None
        self.LGmodesArray__: np.ndarray | None = None
        self.LGmodesArrayFarField__: np.ndarray | None = None
        self.numModes: int | None = None
        self.numModesAll: int | None = None
        self.parameters: dict = {}
        
        #Modes atributes
        self.farfieldGouyPhase = None
  
        if generateModes == True:
        
            self.index = self.computeCoefs()
            modes = self.computeLGmodes(engine, multicore)
            self.LGmodesArray = modes
            self.numModes = modes.shape[0]
            if wholeSet == True:
                modes_all = self.computeAllmodes(multicore)
                self.LGmodesArray__ = modes_all
                self.numModesAll = modes_all.shape[0]            
            if farfield == True:
                self.LGmodesArrayFarField = self.computeFarFieldLGmodes()
                if wholeSet == True:
                    self.LGmodesArrayFarField__ = self.computeAllmodesFarField(multicore)
                           
        self.parameters = self.getSpecs()          
        
    
        
    def __repr__(self):
        
        return( 'LG_object_mfd:%d_group:%i' %(self.parameters['mfd'],self.parameters['mode_group']) )
      
      
    
    #Methods:
        
    def computeCoefs(self):
        xx = self.group
        print('Generating modes coeficients...')
        return( mgcl.graded_index_fiber_coefs(xx))
        
    def updateCoefs(self):
        """ 
        Update or compute coefs in case you changed object atributes 
        
        """
        self.index = mgcl.graded_index_fiber_coefs(self.group)
        
    def computeFarFieldGouyPhase(self):
        xx = self.index
        self.farfieldGouyPhase = mgcl.LGFarFieldGouyPhase(xx)
    
    def computeFarFieldLGmodes(self):
        print('Generating modes at the far field...')
        self.farfieldGouyPhase = mgcl.LGFarFieldGouyPhase(self.index)
        return( mgcl.applyphase(self.LGmodesArray, self.farfieldGouyPhase) )
        
    def computeLGmodes(self, targetEngine, multi) -> np.ndarray:
        print('Generating modes...')
        return cast(
            np.ndarray,
            mgcl.LGmodes(self.w0, self.X, self.Y, self.index, engine=targetEngine, multicore=multi),
        )
    
    def updateLGmodes(self,targetEngine, multi):
         """ 
         Update or compute LGmodes in case you changed object atributes 
         """
         modes = cast(
             np.ndarray,
             mgcl.LGmodes(self.w0, self.X, self.Y, self.index, engine=targetEngine, multicore=multi),
         )
         self.LGmodesArray = modes
         self.numModes = modes.shape[0]
    
    def computeAllmodes(self, multi) -> np.ndarray:
        print('Generating rest of the modes...')
        if self.LGmodesArray is None:
            raise RuntimeError("LGmodesArray is not set; call computeLGmodes first.")
        return mgcl.computeWholeSetofModes(self.LGmodesArray, self.index, multicore=multi)
    
    def computeAllmodesFarField(self, multi):
        print('Generating rest of the modes at the far field...')
        return( mgcl.computeWholeSetofModesFarField( self.LGmodesArray, self.index, self.farfieldGouyPhase, multicore = multi ) )
    
    def updateLGmodesAll(self,multi):
         """ 
         Update or compute LGmodes in case you changed object atributes 
         """
         modes_all = mgcl.computeWholeSetofModes(self.LGmodesArray, self.index, multicore=multi)
         self.LGmodesArray__ = modes_all
         self.numModesAll = modes_all.shape[0]
      
    def getSpecs(self):
        p = {
                      'mfd': (2*self.w0),
                      'mode_group': self.group,
                      'num_samples': self.N,
                      'px_size' : self.px_size,
                      'num_modes' : self.numModes,
                      'num_modes_all' : self.numModesAll,
                      'FarFieldGouy' : self.farfieldGouyPhase,
            }
        self.parameters = p
        return(p)


if __name__ == '__main__':
    import cupy as cp

    print(cp.cuda.Device(0).mem_info)
    mgcl.times.tic()

    LGgpu = LGmodes(48, 22 , 256, 1 , generateModes = True, wholeSet = True, farfield = False, engine = 'GPU', multicore = True)
    mgcl.times.toc()
